#!/bin/bash
#PBS -q {{ executable.pbs_queue }}
#PBS -l {{ executable.pbs_processor }}
#PBS -l {{ executable.pbs_walltime }}
#PBS -N {{ task.get_task_name() }}
#PBS -r n
#PBS -j oe
#PBS -o {{ task.log_file }}

source /etc/profile
module load anaconda/4.3.1

{% for evar in task.environment_vars() %}
export {{ evar }}
{% endfor %}

source activate {{ settings.PBS_CONDA_ENV }}

{{ task.full_executable }}

