# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executable',
            name='remote_queue',
            field=models.CharField(default='pbs', max_length=255),
        ),
    ]
