# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0003_improved_json_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.WorkflowNode'),
        ),
    ]
