# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0004_blank_admin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executable',
            name='environment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='executable',
            name='pbs_executable_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='executable',
            name='static_arguments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
