# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0005_blank_executable_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='executable',
            name='archived',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobqueue',
            name='archived',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='archived',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='archived',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='executable',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
