# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-24 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0006_workflow_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datafix',
        ),
    ]
