# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow_engine', '0007_delete_datafix'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='enqueued_object_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='task',
            name='enqueued_task_object_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='job',
            name='enqueued_object_id',
            field=models.IntegerField(null=True),
        ),
    ]
