# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-01 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def copy_edges(apps, schema_editor):
    WorkflowNode = apps.get_model(
        'workflow_engine',
        'WorkflowNode'
    )
    WorkflowEdge = apps.get_model(
        'workflow_engine',
        'WorkflowEdge'
    )

    nodes = WorkflowNode.objects.all()

    for node in nodes:
        parent = node.parent
        if parent:  # NOTE: workaround for PBS-1921
            if node.archived is True and parent.archived is True:
                archived = True
            else:
                archived = False
        else:
            archived = False

        if parent:
            edge = WorkflowEdge(
                workflow=node.workflow,
                source=parent,
                sink=node,
                disabled=False,
                archived=archived
            )
        else:
            edge = WorkflowEdge(
                workflow=node.workflow,
                source=None,
                sink=node,
                disabled=False,
                archived=archived
            )

        edge.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0008_generic_task_job_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.NullBooleanField(default=False)),
                ('sink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflowedge_sink', to='workflow_engine.WorkflowNode')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflowedge_source', to='workflow_engine.WorkflowNode')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.Workflow')),
            ],
        ),
        migrations.AlterField(
            model_name='executable',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='enqueued_object_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            copy_edges,
            reverse_code=migrations.RunPython.noop
        )
    ]
