# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0009_workflow_edges'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='sinks',
            field=models.ManyToManyField(related_name='sources', through='workflow_engine.WorkflowEdge', to='workflow_engine.WorkflowNode'),
        ),
    ]
