# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0010_source_sink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executable',
            name='pbs_processor',
            field=models.CharField(blank=True, default='vmem=6g', max_length=255),
        ),
        migrations.AlterField(
            model_name='executable',
            name='pbs_queue',
            field=models.CharField(blank=True, default='lims', max_length=255),
        ),
        migrations.AlterField(
            model_name='executable',
            name='pbs_walltime',
            field=models.CharField(blank=True, default='walltime=5:00:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='executable',
            name='remote_queue',
            field=models.CharField(blank=True, default='pbs', max_length=255),
        ),
        migrations.AlterField(
            model_name='executable',
            name='version',
            field=models.CharField(blank=True, default='0.1', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_run_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='enqueued_task_object_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='input_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='log_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='pbs_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='pbs_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_run_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
