# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0011_enqueueable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='content_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
