# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0012_enqueued_object_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='enqueued_task_object_class',
        ),
    ]
