# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-23 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0013_remove_task_object_class_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobqueue',
            name='enqueued_object_class',
        ),
    ]
