# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-13 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0015_more_optional_admin_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='executable',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='jobqueue',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workflow',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workflowedge',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workflownode',
            managers=[
                ('safe_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='executable',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
