# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0016_archive_false_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowedge',
            options={'ordering': ('priority',)},
        ),
        migrations.AddField(
            model_name='workflowedge',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='executable',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
