# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-17 21:29
from __future__ import unicode_literals

from django.db import migrations
import django_fsm

def copy_run_states(apps, schema_editor):
    Job = apps.get_model(
        'workflow_engine',
        'Job'
    )
    Task = apps.get_model(
        'workflow_engine',
        'Task'
    )

    jobs = Job.all_objects.all()
    tasks = Task.all_objects.all()

    for job in jobs:
        job.running_state = job.run_state.name
        job.save()

    for task in tasks:
        task.running_state = task.run_state.name
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0017_edge_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='running_state',
            field=django_fsm.FSMField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='running_state',
            field=django_fsm.FSMField(default='PENDING', max_length=50),
        ),
        migrations.RunPython(
            copy_run_states,
            reverse_code=migrations.RunPython.noop)
    ]
