# Generated by Django 2.2 on 2019-09-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0018_running_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='run_state',
        ),
        migrations.RemoveField(
            model_name='task',
            name='run_state',
        ),
        migrations.DeleteModel(
            name='RunState',
        ),
    ]
